[target.wasm32-wasip1]
rustflags = ['-C', 'target-feature=+simd128', '+relaxed-simd']

[target.wasm32-wasip2]
rustflags = ['-C', 'target-feature=+simd128', '+relaxed-simd']

[target.wasm32-wasip3]
rustflags = ['-C', 'target-feature=+simd128', '+relaxed-simd']