#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "image-conversion"
version = "0.1.0"
authors = ["Karthik Ganeshram <kganeshr@akamai.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "image-conversion"

[component.image-conversion]
source = "target/wasm32-wasip1/release/image_conversion.wasm"
allowed_outbound_hosts = []
[component.image-conversion.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
